# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rw_Metropolis_c <- function(sigma, x0, N) {
    .Call('_StatComp20098_rw_Metropolis_c', PACKAGE = 'StatComp20098', sigma, x0, N)
}

